description: 'd_rap_d95_bIT: The Divergent Net Zero scenario reaches net-zero by 2050
  but with higher costs due to divergent policies introduced across sectors and a
  quicker phase out of fossil fuels. Climate policies are more stringent in the transportation
  and buildings sectors. This mimics a situation where the failure to coordinate policy
  stringency across sectors results in a high burden on consumers, while decarbonisation
  of energy supply and industry is less stringent. Emissions are in line with a climate
  goal giving at least a 50 percent chance of limiting global warming to below 1.5
  K by the end of the century, with no or low overshoot of 1.5 K in earlier years.
  This leads to considerably high transition risks but rather low physical risks.
  Industry sectors are modeled explicitly with individual CES nests for cement, chemicals,
  steel, and other production. The transport model EDGE-T with detailed modes/vehicles
  representation is used. A simple buildings model represents demand in terms of energy
  carriers. Damages from climate change based on Kalkuhl and Wenz (2020) are internalized
  in the optimization using the 95th percentile of RCP26.'
start: '0'
referenceScenario: SSP2-Base_covidCalib_bIT
settings:
  CES_parameters: load
  climate: magicc
  downscaleTemperature: CMIP5
  cm_magicc_calibrateTemperature2000: HADCRUT4
  damages: KWLike
  internalizeDamages: KWlikeItr
  cm_magicc_config: RCP26_95
  cm_magicc_temperatureImpulseResponse: 'on'
  c_CES_calibration_new_structure: 0
  cm_EDGEtr_scen: Mix4
  cm_reducCostB: heatpumps
  cm_CO2TaxSectorMarkup: GLO.trans 2, GLO.build 2
  c_ccsinjecratescen: 2
  cm_rcp_scen: rcp20
  cm_iterative_target_adj: 9
  subsidizeLearning: globallyOptimal
  c_budgetCO2from2020: 560
  carbonprice: diffCurvPhaseIn2Lin
  cm_co2_tax_2020: 200
  cm_peakBudgYr: 2045
  cm_emiscen: 9
  cm_maxProdBiolc: '100'
  techpol: NDC
  cm_startyear: 2025
  path_gdx: SSP2-Base_bIT
  path_gdx_ref: h_ndc_d50_bIT
  path_gdx_bau: SSP2-Base_bIT
