description: 'o_cba_d50_bIT: Cost-benefit analysis, policy driven by Social Cost of
  Carbon only. Damages from climate change based on Kalkuhl and Wenz (2020) are internalized
  in the optimization using the 50th percentile of RCP26.'
start: '0'
referenceScenario: SSP2-Base_covidCalib_bIT
settings:
  CES_parameters: load
  climate: magicc
  downscaleTemperature: CMIP5
  cm_magicc_calibrateTemperature2000: HADCRUT4
  damages: KWLike
  internalizeDamages: KWlikeItr
  cm_magicc_config: RCP26_50
  cm_magicc_temperatureImpulseResponse: 'on'
  c_CES_calibration_new_structure: 0
  cm_EDGEtr_scen: Mix4
  cm_reducCostB: heatpumps
  cm_rcp_scen: rcp26
  subsidizeLearning: globallyOptimal
  c_budgetCO2from2020: 1050
  cm_co2_tax_2020: 100
  cm_peakBudgYr: 2080
  cm_emiscen: 10
  cm_maxProdBiolc: '100'
  techpol: NDC
  cm_startyear: 2025
  path_gdx: o_2c_bIT
  path_gdx_ref: h_ndc_d50_bIT
  path_gdx_bau: SSP2-Base_bIT
